services:
  web:
    build: ./web
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./web/www:/var/www/html/www
    networks:
      - dmz_net
    depends_on:
      - php

  php:
    build:
      context: ./php
    volumes:
      - ./web/www:/var/www/html/www
    networks:
      - dmz_net
      - db_net
    depends_on:
      - db
    env_file:
      - ./db/db.env

  db:
    image: mariadb:latest
    env_file:
      - ./db/db.env
      - ./db/root.env
    volumes:
      - maria-db:/var/lib/mysql
      - ./db/woodytoys.sql:/docker-entrypoint-initdb.d/woodytoys.sql
      - ./db/my-resolve.cnf:/etc/mysql/conf.d/my-resolve.cnf
    networks:
      - db_net

volumes:
  maria-db:

networks:
  dmz_net:
  db_net:
