# Utiliser une image légère de Python
FROM python:3.9-slim

# Définir le dossier de travail dans le conteneur
WORKDIR /app

# Copier le script dans le conteneur
COPY script.py .

# Définir le script comme point d'entrée
CMD ["python", "script.py"]
