services:
  web:
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html
      - ../certificate/letsencrypt/letsencrypt/:/etc/letsencrypt/	
    networks:
      - dmz_net
    depends_on:
      - php

  php:
    build: php
    volumes:
      - ./html/www:/var/www/html/www
    networks:
      - dmz_net
      - db_net
    depends_on:
      - db
    env_file:
      - db.env

  db:
    image: mariadb:11.1
    env_file:
      - ./db/root.env
    volumes:
      - maria-db:/var/lib/mysql
      - ./db/sql/woodytoys.sql:/docker-entrypoint-initdb.d/woodytoys.sql
      - ./db/my-resolve.cnf:/etc/mysql/conf.d/my-resolve.cnf
    networks:
      - db_net

volumes:
  maria-db:

networks:
  dmz_net:
  db_net:
